-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 18:57:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja` (
  `idloja` INT NOT NULL AUTO_INCREMENT,
  `nome_loja` VARCHAR(45) NULL,
  `cidade_loja` VARCHAR(45) NOT NULL,
  `telefone_loja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idloja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `cpf_funcionario` INT NOT NULL,
  `nome_func` VARCHAR(45) NOT NULL,
  `sobrenome_func` VARCHAR(45) NOT NULL,
  `funcao_func` VARCHAR(45) NOT NULL,
  `loja_idloja` INT NOT NULL,
  PRIMARY KEY (`cpf_funcionario`, `loja_idloja`),
  INDEX `fk_funcionario_loja_idx` (`loja_idloja` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_loja`
    FOREIGN KEY (`loja_idloja`)
    REFERENCES `mydb`.`loja` (`idloja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cpf_cliente` CHAR(11) NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `sobrenome_cliente` VARCHAR(45) NOT NULL,
  `telefone_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `telefone_fornecedor` VARCHAR(45) NOT NULL,
  `nome_fornecedor` VARCHAR(45) NULL,
  `fornecedorcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedor`, `fornecedorcol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loja_has_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja_has_fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja_has_fornecedor` (
  `loja_idloja` INT NOT NULL,
  `fornecedor_idfornecedor` INT NOT NULL,
  `fornecedor_fornecedorcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`loja_idloja`, `fornecedor_idfornecedor`, `fornecedor_fornecedorcol`),
  INDEX `fk_loja_has_fornecedor_fornecedor1_idx` (`fornecedor_idfornecedor` ASC, `fornecedor_fornecedorcol` ASC) VISIBLE,
  INDEX `fk_loja_has_fornecedor_loja1_idx` (`loja_idloja` ASC) VISIBLE,
  CONSTRAINT `fk_loja_has_fornecedor_loja1`
    FOREIGN KEY (`loja_idloja`)
    REFERENCES `mydb`.`loja` (`idloja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loja_has_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor` , `fornecedor_fornecedorcol`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor` , `fornecedorcol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente_has_loja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_loja` (
  `Cliente_cpf_cliente` CHAR(11) NOT NULL,
  `loja_idloja` INT NOT NULL,
  PRIMARY KEY (`Cliente_cpf_cliente`, `loja_idloja`),
  INDEX `fk_Cliente_has_loja_loja1_idx` (`loja_idloja` ASC) VISIBLE,
  INDEX `fk_Cliente_has_loja_Cliente1_idx` (`Cliente_cpf_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_loja_Cliente1`
    FOREIGN KEY (`Cliente_cpf_cliente`)
    REFERENCES `mydb`.`Cliente` (`cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_loja_loja1`
    FOREIGN KEY (`loja_idloja`)
    REFERENCES `mydb`.`loja` (`idloja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
